### ISSUE TITLE
AllToAll Functionality for Epiphany

### ISSUE THREAD

**Issue by vanchiramani** [USArmyResearchLab/openshmem-epiphany#2]
Dear Admin

I am trying to do all to all communication in my device program written for Epiphany.
Following is the initialization code:
//id stands for the thread ID.
                        for (j = 0; j < NUM_ROWS; ++j)
                        {
                                offsetj = id*NUM_ROWS + j;
                                local_dataIn[offsetj].real = j;
                                local_dataIn[offsetj].img = offsetj;
                        }
shmem_alltoall64(local_dataIn, local_dataIn, NUM_ROWS, 0, 0, npes, pSyncA);

While doing this only the first NUM_ROWS indices are copied correctly. Is there any thing wrong in the way I am using this function?

Any help appreciated!

**Comment by jamesaross** [comment]
@vanchiramani 
It looks like you may be using it incorrectly, but I don't know what it is you are attempting to do.

I've included the reference for the `shmem_alltoall` routine for further discussion:
> The `shmem_alltoall` routines are collective routines. Each *PE* in the *activeset* exchanges `nelems` data elements of size 32 bits (for `shmem_alltoall32`) or 64 bits (for `shmem_alltoall64`) with all other *PE* in the set. The data being sent and received are stored in a contiguous symmetric data object. The total size of each *PE* `source` object and `dest` object is `nelems` times the size of an element (32 bits or 64 bits) times `PE_size`. The `source` object contains `PE_size` blocks of data (the size of each block defined by `nelems`) and each block of data is sent to a different *PE*. *PE* *i* sends the *j*th block of its `source` object to *PE* *j* and that block of data is placed in the *i*th block of the `dest` object of *PE* *j*.

This means that `local_dataIn` has it's *j*th block (defined by `id` in your code) copied to the *j*th PE.  This is a collective operation and you typically initialize all of the data in your arrays such as:

```c
int npes = shmem_n_pes();
for (int PE_i = 0; PE_i < npes; PE_i++) {
   for (int k = 0; k < NUM_ROWS; k++) {
      int offset = PE_i * NUM_ROWS + k; 
      local_dataIn[offset].real = k;
      local_dataIn[offset].img = offset;
   }
}
```

Modify that code for whatever you're trying to do.

**Comment by vanchiramani** [comment]
@jamesaross 

Thanks a lot for your help. I looked at the manual more carefully and realized that I am looking for fcollect operation. In my scenario, each thread prepares a portion of the data of a large variable and passes to all the other threads. For example, if array size is 100 and there are four threads, thread 0 (T0) computes [0 -24], T1 - [25, 49], T2 - [50, 74] and T3 - [75, 99]. Hence I modified the code as follows:

for (j = 0; j < NUM_ROWS; ++j)
{
    temp_local_dataIn[j].real = j;
    temp_local_dataIn[j].img = j + 2;
}
shmem_fcollect64(local_dataIn, temp_local_dataIn, NUM_ROWS, 0, 0, npes, pSyncA);

I can achieve what I want to do using this. However, I need to use temporary variables and then use the fcollect operation to copy to the large array. I would like to know if there is any method to reuse the large array.

Another question I had is regarding broadcast. Is it possible to send from arbitrary core to all the other cores as the npes parameters and stride only allow me to send data to the cores that have thread_id greater than mine.

**Comment by jamesaross** [comment]
> I would like to know if there is any method to reuse the large array.

I'm not sure what you mean.  If you're referring to `local_dataIn` in your example, you're free to use it again immediately after you've performed the `shmem_fcollect64` operation.

> Another question I had is regarding broadcast. Is it possible to send from arbitrary core to all the other cores as the npes parameters and stride only allow me to send data to the cores that have thread_id greater than mine.

The specification should allow you to send data from an arbitrary core to all other cores provided that it is a strided pattern.  If there is case that is not working for you, it's possible that there is a bug in the library.

This is the prototype:
`shmem_broadcast64(target, source, nelems, PE_root, PE_start, logPE_stride, PE_size, pSync)`

For example, core 5 (`PE_root = 5`) should be able to broadcast data to core 3, 5, 7, 9, 11, and 13 by using a `PE_start = 3`, `logPE_stride = 1`, and `PE_size = 6`.

Now, if you want some arbitrary broadcast pattern that cannot be built from `PE_root`, `PE_start`,  `logPE_stride` and `PE_size`, let's say all prime number cores, you should look at `shmem_put64()`.  You must manually send data to each core in a linear fashion.  The benefits of using `shmem_broadcast64()` are that the other cores can participate in the call in parallel, enabling higher performance.

Good luck.
