### ISSUE TITLE
Allow to cross compile example with e-sdk

### ISSUE THREAD

**Issue by patoperpetua** [USArmyResearchLab/openshmem-epiphany#5]
Hi! I'm using this project in a research. It will be cool if Makefiles use $(gcc) instead of gcc. This will allow to setup any gcc compiler.
Changing this:
`$(gcc) -O3 $< -o $@ $(EINCS) $(ELIBS) -lpthread`
To:
`gcc -O3 $< -o $@ $(EINCS) $(ELIBS) -lpthread`

In every makefile.

**EDIT:**
This was done in every example but in e_hello.

Thanks!

**Comment by jamesaross** [comment]
Hi @patoomnia,

I'm glad to hear you're using it in a research project.  I fixed this for you in commit d3b2acd12fe2afd7a876364a4bb0985c28f41db8

Regards,
James
